export class TodoRepository {
    // Campo privado em javascript
    #database;
    constructor({ database }) {
        this.#database = database;
    }

    async create({ title, description, isFinished = false }) {
        // Create todo item in the database, the run command does not return the inserted object, only the id generated by database
       const result  = await this.#database.run('INSERT INTO todos (title, description, isFinished) VALUES (:title, :description, :isFinished)', {
        ":title": title, 
        ":description": description, 
        ":isFinished": isFinished
       });

       return { id: result.lastID };
    }

    delete({ id }) {
        return this.#database.run('DELETE FROM todos WHERE id = :id', { ":id": id });
    }

    update({ id, title, description, isFinished }) {
        return this.#database.run("UPDATE todos SET title = :title, description = :description, isFinished = :isFinished WHERE id = :id RETURNING *;", {
            ":id": id, 
            ":title": title, 
            ":description": description,
            ":isFinished": isFinished
        });
    }

    read({ id }) {
        return this.#database.get("SELECT id, title, description, isFinished FROM todos WHERE id = :id;", {
            ":id": id
        });
    }
}